name = "JuliaExplorations"
uuid = "63482e45-837b-423e-990a-4dca00312bbd"
authors = ["mbeltagy <mohammed.elbeltagy@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
